// ─── Nokma string table ───────────────────────────────────────────────────
// Every user-facing string lives here, keyed by a stable ID. Add new strings as
// [english, filipino] pairs — the second slot is required so a missing
// translation is a type error rather than a silent English fallback at runtime.
//
// Placeholders use {name} syntax and are filled by t()'s params argument.

export const STRINGS = {
  // ── Common / shared ────────────────────────────────────────────────────────
  'common.yes':            ['Yes', 'Oo'],
  'common.no':             ['No', 'Hindi'],
  'common.cancel':         ['Cancel', 'Kanselahin'],
  'common.ok':             ['OK', 'OK'],
  'common.save':           ['Save', 'I-save'],
  'common.delete':         ['Delete', 'Burahin'],
  'common.error':          ['Error', 'May mali'],
  'common.confirm':        ['Confirm', 'Kumpirmahin'],
  'common.continue':       ['Continue', 'Magpatuloy'],
  'common.back':           ['Back', 'Bumalik'],
  'common.next':           ['Next', 'Susunod'],
  'common.done':           ['Done', 'Tapos na'],
  'common.skip':           ['Skip', 'Laktawan'],
  'common.exit':           ['Exit', 'Lumabas'],
  'common.none':           ['None', 'Wala'],
  'common.unknown':        ['Unknown', 'Hindi alam'],
  'common.preferNotToSay': ['Prefer not to say', 'Mas gusto kong hindi sumagot'],
  'common.other':          ['Other / not listed', 'Iba pa / wala sa listahan'],
  'common.otherOptional':  ['Other (optional)', 'Iba pa (opsyonal)'],
  'common.pleaseSpecify':  ['Please specify', 'Pakitukoy'],
  'common.selected':       ['selected', 'napili'],
  'common.notSelected':    ['not selected', 'hindi napili'],
  'common.options':        ['Options', 'Mga opsyon'],
  'common.notSet':         ['Not set', 'Hindi nakatakda'],
  'common.tapToSkip':      ['Tap to skip', 'I-tap para laktawan'],
  'common.close':          ['Close', 'Isara'],
  /** Joiner for two-item lists, e.g. "Lunch and Dinner". Spaces are added by the caller. */
  'common.and':            ['and', 'at'],

  'validation.required':   ['Required', 'Kinakailangan'],


  // Input placeholders. Example values stay recognisable in both languages.
  'ph.exampleName':       ['e.g. Protein Bar', 'hal. Protein Bar'],
  'ph.exampleMenuItem':   ['e.g. 1pc Chickenjoy', 'hal. 1pc Chickenjoy'],
  'ph.exampleRestaurant': ['e.g. Jollibee', 'hal. Jollibee'],
  'ph.exampleGrams':      ['e.g. 150', 'hal. 150'],
  'ph.exampleBones':      ['e.g. 20', 'hal. 20'],

  // ── Macros / nutrition vocabulary ──────────────────────────────────────────
  'macro.calories': ['Calories', 'Calories'],
  'macro.protein':  ['Protein', 'Protina'],
  'macro.carbs':    ['Carbs', 'Carbs'],
  'macro.fat':      ['Fat', 'Taba'],
  'macro.kcal':     ['kcal', 'kcal'],
  'macro.proteinG': ['Protein (g)', 'Protina (g)'],
  'macro.carbsG':   ['Carbs (g)', 'Carbs (g)'],
  'macro.fatG':     ['Fat (g)', 'Taba (g)'],
  'macro.grams':    ['g', 'g'],

  // ── Meal types ─────────────────────────────────────────────────────────────
  'meal.breakfast': ['Breakfast', 'Almusal'],
  'meal.lunch':     ['Lunch', 'Tanghalian'],
  'meal.dinner':    ['Dinner', 'Hapunan'],
  'meal.snack':     ['Snack', 'Meryenda'],

  // ── Cooking methods ────────────────────────────────────────────────────────
  'cooking.raw':        ['Raw', 'Hilaw'],
  'cooking.boiled':     ['Boiled', 'Nilaga'],
  'cooking.steamed':    ['Steamed', 'Pinasingawan'],
  'cooking.grilled':    ['Grilled', 'Inihaw'],
  'cooking.baked':      ['Baked', 'Hinurno'],
  'cooking.fried':      ['Fried', 'Pinirito'],
  'cooking.deep_fried': ['Deep Fried', 'Malalim na pagprito'],
  'cooking.sauteed':    ['Sautéed', 'Ginisa'],
  'cooking.stewed':     ['Stewed', 'Nilaga sa sarsa'],
  'cooking.roasted':    ['Roasted', 'Inihaw sa oven'],

  // ── Goals ──────────────────────────────────────────────────────────────────
  'goal.lose':         ['Lose weight', 'Magpapayat'],
  'goal.maintain':     ['Maintain weight', 'Panatilihin ang timbang'],
  'goal.gain':         ['Gain weight', 'Dumagdag ng timbang'],
  'goal.build_habits': ['Build healthier habits', 'Bumuo ng mas malusog na gawi'],

  // ── Tabs ───────────────────────────────────────────────────────────────────
  'tab.dashboard': ['Dashboard', 'Dashboard'],
  'tab.coach':     ['Nokma', 'Nokma'],
  'tab.search':    ['Search', 'Maghanap'],
  'tab.log':       ['Log Meal', 'Mag-log'],
  'tab.profile':   ['Profile', 'Profile'],

  'dash.steps':    ['Steps', 'Hakbang'],

  // ── Onboarding ─────────────────────────────────────────────────────────────
  'onboarding.selectLanguage': ['Select your language', 'Pumili ng wika'],
  'onboarding.exitTitle':      ['Exit setup?', 'Lumabas sa setup?'],
  'onboarding.exitBody': [
    'Your progress will be saved. You can continue later.',
    'Ang iyong progreso ay mai-save. Maaari kang magpatuloy mamaya.',
  ],
  'onboarding.exitSetup':   ['Exit setup', 'Lumabas sa setup'],
  'onboarding.namePlaceholder': ['Your name', 'Ang iyong pangalan'],
  'onboarding.agePlaceholder':  ['Your age', 'Ang iyong edad'],
  'onboarding.height':          ['Height', 'Taas'],
  'onboarding.weight':          ['Weight', 'Timbang'],
  'onboarding.male':            ['Male', 'Lalaki'],
  'onboarding.female':          ['Female', 'Babae'],
  'onboarding.goToDashboard':   ['Go to Dashboard', 'Pumunta sa Dashboard'],

  'onboarding.welcome': [
    "Hi! I'm Nokma, your coach for tracking meals, calories, and healthy habits. What should I call you?",
    'Kumusta! Ako si Nokma, ang iyong coach para sa pag-track ng pagkain, calories, at malusog na gawi. Ano ang gusto mong itawag ko sa iyo?',
  ],
  'onboarding.sexMessage': [
    "Got it! To give you accurate calorie and macro goals, what is your biological sex?",
    "Nakuha ko! Para mabigyan kita ng tumpak na calorie at macro goals, ano ang iyong biological sex?",
  ],
  'onboarding.age': [
    'Nice to meet you, {name}! How old are you?',
    'Ikinagagalak kitang makilala, {name}! Ilang taon ka na?',
  ],
  'onboarding.heightWeight': [
    "Let's set up your starting point. Enter your height and weight — you can choose cm or ft/in, and kg or lb.",
    'I-set up natin ang iyong panimulang datos. Ilagay ang iyong taas at timbang — pwedeng cm o ft/in, at kg o lb.',
  ],
  'onboarding.feedback': [
    "Thanks, {name}. This helps me personalize your tracking experience. We'll take this one step at a time.",
    'Salamat, {name}. Nakakatulong ito para ma-personalize ko ang iyong tracking experience. Isa-isa nating gagawin ito.',
  ],
  'onboarding.goalQuestion': [
    'What would you like to focus on?',
    'Ano ang gusto mong pagtuunan?',
  ],
  'onboarding.goalSuggestion': [
    'Based on what you shared, one option you may want to consider is {goal}, but you are always in control of your goal.',
    'Batay sa iyong ibinahagi, isang opsyon na maaari mong pag-isipan ay ang {goal}, pero ikaw pa rin ang may kontrol sa iyong goal.',
  ],
  'onboarding.finish': [
    "You're all set, {name}! I'll be here to help you track your progress, celebrate your consistency, and take things one day at a time.",
    'Handa ka na, {name}! Nandito ako para tulungan kang i-track ang iyong progress, ipagdiwang ang iyong consistency, at gawin ang mga bagay isa-isa.',
  ],

  // Health conditions
  'onboarding.healthQuestion': [
    'Do you have any health conditions that may affect food, activity, or nutrition planning?',
    'Mayroon ka bang mga kondisyong pangkalusugan na maaaring makaapekto sa pagkain, aktibidad, o nutrisyon?',
  ],
  'onboarding.healthNo': [
    "Thanks for letting me know. I'll keep your plan simple and focused on your goals.",
    'Salamat sa pagsagot. Pananatilihin kong simple at nakatutok ang iyong plano sa iyong mga goal.',
  ],
  'onboarding.healthWhich': [
    'Which condition(s) apply to you?',
    'Aling kondisyon ang naaangkop sa iyo?',
  ],
  'onboarding.healthSafety': [
    'Nokma can support general tracking. For condition-specific food, calorie, medication, or activity advice, please follow guidance from your doctor or registered dietitian.',
    'Ang Nokma ay maaaring sumuporta sa general tracking. Para sa payo tungkol sa partikular na kondisyon — pagkain, calorie, gamot, o aktibidad — mangyaring sumunod sa gabay ng iyong doktor o rehistradong dietitian.',
  ],
  'onboarding.searchConditions': ['Search conditions...', 'Maghanap ng kondisyon...'],

  // Allergies
  'onboarding.allergiesQuestion': [
    'Do you have any food allergies or foods you need to avoid?',
    'Mayroon ka bang mga allergy sa pagkain o pagkain na kailangan mong iwasan?',
  ],
  'onboarding.allergiesNo': [
    'Great! I will not filter any foods out for you.',
    'Magaling! Hindi ako mag-filter ng anumang pagkain para sa iyo.',
  ],
  'onboarding.allergiesSelect': ['Select any that apply:', 'Piliin ang mga naaangkop:'],
  'onboarding.allergySafety': [
    'Always check food labels and ask a healthcare professional for guidance about allergies or severe reactions.',
    'Palaging suriin ang mga food label at magtanong sa isang healthcare professional para sa gabay tungkol sa mga allergy o matinding reaksyon.',
  ],
  'onboarding.searchAllergens': ['Search allergens...', 'Maghanap ng allergen...'],
  'onboarding.intolerancesTitle': [
    'Food intolerances or sensitivities',
    'Food intolerance o sensitivity',
  ],
  'onboarding.intolerancesHint': [
    'Examples: lactose intolerance, gluten sensitivity, spicy foods, caffeine sensitivity',
    'Halimbawa: lactose intolerance, gluten sensitivity, maanghang na pagkain, caffeine sensitivity',
  ],
  'onboarding.intolerancesPlaceholder': [
    'Describe your intolerances...',
    'Ilarawan ang iyong mga intolerance...',
  ],

  // Validation
  'validation.name':   ['Please enter your name.', 'Pakilagay ang iyong pangalan.'],
  'validation.age':    ['Please enter a valid age (10–120).', 'Pakilagay ang wastong edad (10–120).'],
  'validation.height': ['Please enter a valid height.', 'Pakilagay ang wastong taas.'],
  'validation.weight': ['Please enter a valid weight.', 'Pakilagay ang wastong timbang.'],

  // ── Health condition options ───────────────────────────────────────────────
  'cat.metabolic':  ['Metabolic / endocrine', 'Metabolic / endocrine'],
  'cat.heart':      ['Heart / circulation', 'Puso / sirkulasyon'],
  'cat.digestive':  ['Digestive', 'Panunaw'],
  'cat.kidneyLiver':['Kidney / liver', 'Bato / atay'],
  'cat.boneBlood':  ['Bone / blood', 'Buto / dugo'],
  'cat.otherDiet':  ['Other diet-related contexts', 'Iba pang konteksto kaugnay ng diyeta'],

  'cond.type1_diabetes':       ['Type 1 diabetes', 'Type 1 diabetes'],
  'cond.type2_diabetes':       ['Type 2 diabetes', 'Type 2 diabetes'],
  'cond.prediabetes':          ['Prediabetes', 'Prediabetes'],
  'cond.pcos':                 ['PCOS', 'PCOS'],
  'cond.hypothyroidism':       ['Hypothyroidism', 'Hypothyroidism'],
  'cond.hyperthyroidism':      ['Hyperthyroidism', 'Hyperthyroidism'],
  'cond.high_blood_pressure':  ['High blood pressure', 'Altapresyon'],
  'cond.high_cholesterol':     ['High cholesterol', 'Mataas na kolesterol'],
  'cond.heart_disease':        ['Heart disease', 'Sakit sa puso'],
  'cond.heart_failure':        ['Heart failure', 'Heart failure'],
  'cond.celiac':               ['Celiac disease', 'Celiac disease'],
  'cond.ibs':                  ['Irritable bowel syndrome (IBS)', 'Irritable bowel syndrome (IBS)'],
  'cond.ibd':                  ["Inflammatory bowel disease (Crohn's / ulcerative colitis)", 'Inflammatory bowel disease (Crohn’s / ulcerative colitis)'],
  'cond.gerd':                 ['GERD / acid reflux', 'GERD / acid reflux'],
  'cond.chronic_constipation': ['Chronic constipation', 'Talamak na constipation'],
  'cond.ckd':                  ['Chronic kidney disease', 'Talamak na sakit sa bato'],
  'cond.kidney_stones':        ['Kidney stones', 'Bato sa bato'],
  'cond.fatty_liver':          ['Fatty liver disease', 'Fatty liver disease'],
  'cond.liver_disease':        ['Liver disease', 'Sakit sa atay'],
  'cond.iron_deficiency':      ['Iron-deficiency anemia', 'Anemia dahil sa kakulangan ng iron'],
  'cond.osteoporosis':         ['Osteoporosis', 'Osteoporosis'],
  'cond.gout':                 ['Gout / high uric acid', 'Gout / mataas na uric acid'],
  'cond.pregnancy':            ['Pregnancy', 'Pagbubuntis'],
  'cond.breastfeeding':        ['Breastfeeding', 'Pagpapasuso'],
  'cond.eating_disorder':      ['Eating disorder or history of disordered eating', 'Eating disorder o kasaysayan ng disordered eating'],

  // ── Allergen options ───────────────────────────────────────────────────────
  'cat.commonAllergens': ['Common allergens', 'Karaniwang allergen'],
  'cat.shellfish':       ['Shellfish & mollusks', 'Shellfish at mollusk'],
  'cat.otherAllergens':  ['Other allergens', 'Iba pang allergen'],
  'cat.fruits':          ['Fruits', 'Prutas'],

  'allergen.milk':       ['Milk / dairy', 'Gatas / dairy'],
  'allergen.egg':        ['Egg', 'Itlog'],
  'allergen.peanut':     ['Peanut', 'Mani'],
  'allergen.tree_nuts':  ['Tree nuts', 'Tree nuts'],
  'allergen.soy':        ['Soy', 'Toyo / soy'],
  'allergen.wheat':      ['Wheat', 'Trigo'],
  'allergen.sesame':     ['Sesame', 'Linga'],
  'allergen.fish':       ['Fish', 'Isda'],
  'allergen.crustacean': ['Crustacean shellfish (shrimp, crab, lobster)', 'Crustacean (hipon, alimango, lobster)'],
  'allergen.mollusks':   ['Mollusks (squid, oyster, mussel, clam)', 'Mollusk (pusit, talaba, tahong, halaan)'],
  'allergen.corn':       ['Corn', 'Mais'],
  'allergen.coconut':    ['Coconut', 'Niyog'],
  'allergen.mustard':    ['Mustard', 'Mustasa'],
  'allergen.celery':     ['Celery', 'Kintsay'],
  'allergen.lupin':      ['Lupin', 'Lupin'],
  'allergen.sulfites':   ['Sulfites', 'Sulfite'],
  'allergen.kiwi':       ['Kiwi', 'Kiwi'],
  'allergen.banana':     ['Banana', 'Saging'],
  'allergen.avocado':    ['Avocado', 'Abokado'],
  'allergen.strawberry': ['Strawberry', 'Strawberry'],

  // ── Dashboard ──────────────────────────────────────────────────────────────
  'dash.todaysMeals':   ["Today's Meals", 'Mga Pagkain Ngayon'],
  'dash.add':           ['Add', 'Idagdag'],
  'dash.logAMeal':      ['Log a Meal', 'Mag-log ng Pagkain'],
  'dash.goodMorning':   ['Good morning!', 'Magandang umaga!'],
  'dash.goodAfternoon': ['Good afternoon!', 'Magandang hapon!'],
  'dash.goodEvening':   ['Good evening!', 'Magandang gabi!'],
  'dash.emptyMeals': [
    "Nokma hasn't seen any meals yet today. Time to log your first one!",
    'Wala pang nakikitang pagkain si Nokma ngayong araw. Oras na para mag-log ng una mo!',
  ],
  'dash.logged': ['Logged! Keep up the great tracking!', 'Na-log! Ipagpatuloy ang magandang pag-track!'],

  // ── Meal section (expandable meal card) ────────────────────────────────────
  'mealSection.recipe':        ['Recipe', 'Recipe'],
  'mealSection.itemCount':     ['{count} items', '{count} item'],
  'mealSection.noItems':       ['No items logged', 'Walang na-log na item'],
  'mealSection.alignment':     ['Meal Macro Alignment ({pct}% daily target)', 'Meal Macro Alignment ({pct}% ng pang-araw-araw na target)'],
  'mealSection.ingredients':   ['Recipe Ingredients (scaled to {grams}g portion):', 'Mga Sangkap ng Recipe (naka-scale sa {grams}g na bahagi):'],
  'mealSection.bones':         ['{grams}g bones', '{grams}g buto'],
  'mealSection.withBones':     ['with bones', 'may buto'],
  'mealSection.item':          ['Item', 'Item'],

  // ── Coach messages (dashboard) ─────────────────────────────────────────────
  'coach.greeting.morning':   ['Good morning, {name}!', 'Magandang umaga, {name}!'],
  'coach.greeting.afternoon': ['Good afternoon, {name}!', 'Magandang hapon, {name}!'],
  'coach.greeting.evening':   ['Good evening, {name}!', 'Magandang gabi, {name}!'],
  'coach.friend':             ['there', 'kaibigan'],
  'coach.lateNight': [
    "It's getting late! Great work today. Time to rest and recover.",
    'Gumagabi na! Magaling ang ginawa mo ngayong araw. Oras na para magpahinga.',
  ],
  'coach.welcome': [
    "Welcome to Nokma! Tap the + to log your first meal — I'll help track your progress!",
    'Maligayang pagdating sa Nokma! I-tap ang + para i-log ang unang pagkain mo — tutulungan kitang i-track ang progress mo!',
  ],
  'coach.celebration': [
    'Nailed it! All macros hit today. Nokma is proud of you!',
    'Nagawa mo! Kumpleto ang macros ngayong araw. Proud sa iyo si Nokma!',
  ],
  'coach.almostThere':      ['Almost there! {remainder}. You\'ve got this!', 'Malapit na! {remainder}. Kaya mo yan!'],
  'coach.proteinToGo':      ['{grams}g protein to go', '{grams}g protina na lang'],
  'coach.bitMore':          ['just a bit more to hit your goals', 'kaunti na lang para maabot ang iyong mga goal'],
  'coach.goodProgress':     ['Good progress! {count} meal logged. Keep it going!', 'Magandang progreso! {count} pagkain ang na-log. Ituloy mo lang!'],
  'coach.goodProgressPlural': ['Good progress! {count} meals logged. Keep it going!', 'Magandang progreso! {count} pagkain ang na-log. Ituloy mo lang!'],
  'coach.greatStart': [
    "Great start! You've logged {count} meals. Try for a balanced dinner to round things out.",
    'Magandang simula! {count} pagkain na ang na-log mo. Subukan ang balanseng hapunan para makumpleto.',
  ],
  'coach.offToGoodStart': [
    "You're off to a good start! What's next on your menu today?",
    'Maganda ang simula mo! Ano ang susunod sa menu mo ngayong araw?',
  ],
  'coach.startLogging': [
    'Start logging your meals to see your progress!',
    'Simulan ang pag-log ng iyong pagkain para makita ang progress mo!',
  ],

  // ── Tutorial ───────────────────────────────────────────────────────────────
  'tutorial.welcome.title': ['Welcome to Nokma!', 'Maligayang pagdating sa Nokma!'],
  'tutorial.welcome.body': [
    "Hi {name}! I'm your guide through this app. Let me show you around so you can start tracking your nutrition with confidence.",
    'Kumusta {name}! Ako ang iyong gabay sa app na ito. Ipapakita ko sa iyo ang paligid para makapagsimula kang mag-track nang may kumpiyansa.',
  ],
  'tutorial.log.title': ['Log Your Meals', 'I-log ang Iyong Pagkain'],
  'tutorial.log.body': [
    "Tap the + button to record what you eat. Tell me the food and I'll calculate the macros for you.",
    'I-tap ang + button para itala ang kinain mo. Sabihin mo ang pagkain at kakalkulahin ko ang macros para sa iyo.',
  ],
  'tutorial.track.title': ['Track Your Progress', 'I-track ang Iyong Progreso'],
  'tutorial.track.body': [
    'Your calorie tracker and macro bars show how close you are to your daily targets. The fuller they are, the better!',
    'Ipinapakita ng iyong calorie tracker at macro bars kung gaano ka na kalapit sa iyong pang-araw-araw na target. Mas puno, mas maganda!',
  ],
  'tutorial.coach.title': ['Nokma Responds', 'Sumasagot si Nokma'],
  'tutorial.coach.body': [
    'I read your activity and give you tailored feedback, encouragement, and tips to keep you on track.',
    'Binabasa ko ang iyong aktibidad at nagbibigay ng angkop na feedback, paghihikayat, at tips para manatili kang nasa tamang landas.',
  ],
  'tutorial.ready.title': ["You're Ready!", 'Handa Ka Na!'],
  'tutorial.ready.body': [
    "Log your first entry and I'll guide you from there.",
    'I-log ang iyong unang entry at gagabayan kita mula doon.',
  ],

  // ── Log Meal screen ────────────────────────────────────────────────────────
  'log.title':          ['Log Meal', 'Mag-log ng Pagkain'],
  'log.itemsToLog':     ['Items to Log ({count})', 'Mga Item na Ilo-log ({count})'],
  'log.manualEntry':    ['Manual Entry', 'Manual na Pag-input'],
  'log.submit':         ['Log {mealType} ({count} items)', 'I-log ang {mealType} ({count} item)'],
  'log.noItemsTitle':   ['No items', 'Walang item'],
  'log.noItemsBody':    ['Add at least one food item before logging.', 'Magdagdag ng kahit isang pagkain bago mag-log.'],
  'log.successTitle':   ['Meal logged!', 'Na-log ang pagkain!'],
  'log.successBody':    ['{mealType} logged with {count} item', 'Na-log ang {mealType} na may {count} item'],
  'log.successBodyPlural': ['{mealType} logged with {count} items', 'Na-log ang {mealType} na may {count} item'],
  'log.failedTitle':    ['Logging Failed', 'Nabigo ang Pag-log'],
  'log.failedBody':     ['Could not log meal.', 'Hindi ma-log ang pagkain.'],
  'log.allergenTitle':  ['Allergy alert ⚠️', 'Alerto sa allergy ⚠️'],
  'log.allergenBody':   ['This contains allergens you registered: {allergens}', 'Naglalaman ito ng allergen na mayroon ka: {allergens}'],
  'log.logAnyway':      ['Log anyway', 'I-log pa rin'],

  // Manual entry form
  'form.foodType':       ['Food Type', 'Uri ng Pagkain'],
  'form.foodPlaceholder':['Or type a food name...', 'O mag-type ng pangalan ng pagkain...'],
  'form.cookingMethod':  ['Cooking Method', 'Paraan ng Pagluluto'],
  'form.amountGrams':    ['Amount (grams)', 'Dami (gramo)'],
  'form.hasBones':       ['Has Bones?', 'May Buto?'],
  'form.bonesHint':      ['Input the weight of the bones in grams', 'Ilagay ang bigat ng buto sa gramo'],
  'form.boneWeight':     ['Bone Weight (grams)', 'Bigat ng Buto (gramo)'],
  'form.manualMacros':   ['Enter Macros Manually?', 'Manual na Ilagay ang Macros?'],
  'form.addToMeal':      ['Add to Meal', 'Idagdag sa Pagkain'],
  'form.errFoodType':    ['Enter a food type', 'Ilagay ang uri ng pagkain'],
  'form.errWeight':      ['Enter a valid weight (g)', 'Ilagay ang wastong bigat (g)'],
  'form.liveAllergen':   ['Contains allergens you have: {allergens}', 'Naglalaman ng allergen mo: {allergens}'],

  // ── Search screen ──────────────────────────────────────────────────────────
  'search.title':          ['Find Food', 'Maghanap ng Pagkain'],
  'search.placeholder':    ['Search {tab}...', 'Maghanap ng {tab}...'],
  'search.tabFoods':       ['Foods & Recipes', 'Pagkain at Recipe'],
  'search.tabRestaurant':  ['Fast Food', 'Fast Food'],
  'search.scanMenu':       ['Scan Menu', 'I-scan ang Menu'],
  'search.addManually':    ['Add Manually', 'Manual na Idagdag'],
  'search.addCustomFood':  ['Add Custom Food', 'Magdagdag ng Custom na Pagkain'],
  'search.noResults':      ['No results found.', 'Walang nahanap na resulta.'],
  'search.noFastFood':     ['No custom fast foods yet.', 'Wala pang custom na fast food.'],
  'search.fastFoodHint': [
    "Tap 'Scan Menu' or 'Add Manually' to store your favorite fast food macros for easy logging!",
    "I-tap ang 'I-scan ang Menu' o 'Manual na Idagdag' para i-save ang macros ng paborito mong fast food!",
  ],
  'search.phFoods':          ['Search foods...', 'Maghanap ng pagkain...'],
  'search.phRestaurant':     ['Search fast food...', 'Maghanap ng fast food...'],
  'search.scan':             ['Scan', 'I-scan'],
  'search.custom':           ['Custom', 'Custom'],
  'search.deleteCustomFood': ['Delete Custom Food', 'Burahin ang Custom na Pagkain'],
  'search.deleteFastFood':   ['Delete Fast Food', 'Burahin ang Fast Food'],
  'search.addFastFood':      ['Add Fast Food', 'Magdagdag ng Fast Food'],
  'search.name':             ['Name', 'Pangalan'],
  'search.restaurant':       ['Restaurant', 'Restaurant'],
  'search.saveItem':         ['Save Item', 'I-save ang Item'],
  'search.nameRequired':     ['Name is required', 'Kailangan ang pangalan'],
  'search.typeSource':       ['Type / Source', 'Uri / Pinagmulan'],
  'search.macrosBreakdown':  ['Macros Breakdown', 'Detalye ng Macros'],
  'search.servingSize':      ['Serving size: {grams}g', 'Laki ng serving: {grams}g'],
  'search.containsAllergen': ['Contains allergen: {allergens}', 'Naglalaman ng allergen: {allergens}'],
  'search.ingredients':      ['Ingredients ({grams}g portion):', 'Sangkap ({grams}g na bahagi):'],
  'search.selectMealType':   ['Select meal type to log "{name}":', 'Piliin ang uri ng pagkain para i-log ang "{name}":'],
  'search.loggedTitle':      ['Logged! 🎉', 'Na-log! 🎉'],
  'search.loggedBody':       ['{name} ({grams}g) has been added to your {mealType}.', 'Naidagdag ang {name} ({grams}g) sa iyong {mealType}.'],
  'search.couldNotLog':      ['Could not log meal', 'Hindi ma-log ang pagkain'],
  'search.logThisItem':      ['Log this item', 'I-log ang item na ito'],
  'search.scannedMenuItem':  ['Scanned Menu Item', 'Na-scan na Item sa Menu'],
  'search.customFastFood':   ['Custom Fast Food', 'Custom na Fast Food'],
  'search.srcRecipe':        ['🇵🇭 Recipe ({country})', '🇵🇭 Recipe ({country})'],
  'search.srcRestaurant':    ['🍔 Fast Food ({restaurant})', '🍔 Fast Food ({restaurant})'],
  'search.srcFood':          ['🍎 Food ({category})', '🍎 Pagkain ({category})'],
  'search.categoryGeneral':  ['general', 'pangkalahatan'],
  'card.per100gRaw':         ['per 100g raw', 'kada 100g hilaw'],
  'card.per100g':            ['per 100g', 'kada 100g'],
  'card.recipePortion':      ['🇵🇭 {country} · {grams}g portion', '🇵🇭 {country} · {grams}g na bahagi'],
  'card.recipePer100g':      ['🇵🇭 {country} · per 100g', '🇵🇭 {country} · kada 100g'],

  // ── Camera / OCR ───────────────────────────────────────────────────────────
  'ocr.permissionDenied':      ['Permission Denied', 'Tinanggihan ang Pahintulot'],
  'ocr.cameraRequiredMenu':    ['Camera access is required to scan menus.', 'Kailangan ang access sa camera para mag-scan ng menu.'],
  'ocr.cameraRequiredLabel':   ['Camera access is required to scan nutrition facts.', 'Kailangan ang access sa camera para mag-scan ng nutrition facts.'],
  'ocr.simulatedTitle':        ['Simulated OCR', 'Simulated na OCR'],
  'ocr.simulatedMenuBody': [
    'In a production app with a backend server, we would run AI OCR here to extract calories from the image. For now, please input the macros manually!',
    'Sa production app na may backend server, magpapatakbo tayo ng AI OCR dito para kunin ang calories mula sa larawan. Sa ngayon, pakilagay ang macros nang manual!',
  ],
  'ocr.simulatedLabelBody': [
    'In a production app with a backend server, we would run AI OCR here to extract macros from the nutrition label. For now, please input the macros manually!',
    'Sa production app na may backend server, magpapatakbo tayo ng AI OCR dito para kunin ang macros mula sa nutrition label. Sa ngayon, pakilagay ang macros nang manual!',
  ],
  'ocr.addScanned':   ['Add Scanned Nutrition Facts', 'Idagdag ang Na-scan na Nutrition Facts'],
  'ocr.foodName':     ['Food Name', 'Pangalan ng Pagkain'],
  'ocr.mealType':     ['Meal Type', 'Uri ng Pagkain'],
  'ocr.logToMeal':    ['Log to Meal', 'I-log sa Pagkain'],
  'ocr.nameRequired': ['Food name is required', 'Kailangan ang pangalan ng pagkain'],
  'ocr.failedLog':    ['Failed to log scanned meal', 'Nabigong i-log ang na-scan na pagkain'],

  // ── Profile ────────────────────────────────────────────────────────────────
  'profile.dailyTargets':   ['Daily Targets', 'Pang-araw-araw na Target'],
  'profile.bodyStats':      ['Body Stats', 'Sukat ng Katawan'],
  'profile.healthInfo':     ['Health Info', 'Impormasyong Pangkalusugan'],
  'profile.age':            ['Age', 'Edad'],
  'profile.ageValue':       ['{age} years', '{age} taon'],
  'profile.sex':            ['Sex', 'Kasarian'],
  'profile.male':           ['Male', 'Lalaki'],
  'profile.female':         ['Female', 'Babae'],
  'profile.height':         ['Height', 'Taas'],
  'profile.weight':         ['Weight', 'Timbang'],
  'profile.country':        ['Country', 'Bansa'],
  'profile.condition':      ['Condition', 'Kondisyon'],
  'profile.allergies':      ['Allergies', 'Mga Allergy'],
  'profile.otherCondition': ['Other condition', 'Ibang kondisyon'],
  'profile.activity':       ['Activity', 'Aktibidad'],
  'profile.language':       ['Language', 'Wika'],
  'profile.languageHint': [
    'Nokma will speak to you in this language.',
    'Sa wikang ito magsasalita si Nokma sa iyo.',
  ],
  'activity.1': ['Sedentary', 'Halos hindi gumagalaw'],
  'activity.2': ['Lightly Active', 'Bahagyang aktibo'],
  'activity.3': ['Moderately Active', 'Katamtamang aktibo'],
  'activity.4': ['Very Active', 'Napakaaktibo'],
  'activity.5': ['Super Active', 'Sobrang aktibo'],
  'lang.english':  ['English', 'Ingles'],
  'lang.filipino': ['Filipino', 'Filipino'],
  'profile.replayTutorial': ['Replay Tutorial', 'Ulitin ang Tutorial'],
  'profile.tutorialReset':  ['Tutorial Reset', 'Na-reset ang Tutorial'],
  'profile.tutorialResetBody': [
    'The Nokma tutorial will appear again on your next dashboard visit.',
    'Lilitaw muli ang tutorial ni Nokma sa susunod mong pagbisita sa dashboard.',
  ],
  'profile.resetProgress':     ['Reset All Progress', 'I-reset ang Lahat ng Progreso'],
  'profile.resetTitle':        ['Reset Progress', 'I-reset ang Progreso'],
  'profile.resetBody': [
    'This will delete all your data and progress. Are you sure?',
    'Buburahin nito ang lahat ng iyong data at progreso. Sigurado ka ba?',
  ],
  'profile.resetConfirm':      ['Reset Everything', 'I-reset ang Lahat'],
  'profile.goalLose':          ['🔥 Lose Weight', '🔥 Magpapayat'],
  'profile.goalGain':          ['💪 Gain Muscle', '💪 Magpalaki ng Muscle'],
  'profile.goalMaintain':      ['⚖️ Maintain', '⚖️ Panatilihin'],
  'profile.picture':           ['Profile Picture', 'Larawan sa Profile'],
  'profile.pictureAction':     ['What would you like to do?', 'Ano ang gusto mong gawin?'],
  'profile.removePhoto':       ['Remove Photo', 'Alisin ang Larawan'],
  'profile.choosePhoto':       ['Choose New Photo', 'Pumili ng Bagong Larawan'],
  'profile.photoPermission': [
    'Nokma needs access to your photos to change your profile picture.',
    'Kailangan ni Nokma ng access sa iyong mga larawan para mapalitan ang profile picture mo.',
  ],
  'profile.photoFailed':  ['Failed to pick image from library.', 'Nabigong pumili ng larawan mula sa library.'],
  'profile.defaultName':  ['Nokma User', 'Nokma User'],
  'profile.version':      ['Nokma v1.0.0 · Built for 🇵🇭', 'Nokma v1.0.0 · Ginawa para sa 🇵🇭'],
  'profile.bmi':          ['BMI', 'BMI'],
  'profile.bmiUnderweight':['Underweight', 'Kulang sa timbang'],
  'profile.bmiNormal':     ['Normal', 'Normal'],
  'profile.bmiOverweight': ['Overweight', 'Sobra sa timbang'],
  'profile.bmiObese':      ['Obese', 'Obese'],

  // ── Chat ───────────────────────────────────────────────────────────────────
  'chat.inputPlaceholder': ['Chat or type what you ate to log...', 'Mag-chat o i-type ang kinain mo para i-log...'],
  'chat.writing':          ['Nokma is writing...', 'Nagsusulat si Nokma...'],
  'chat.statusMotivated':  ['Feeling motivated!', 'Motivated ako!'],
  'chat.statusSleepy':     ['Getting sleepy... Zzz', 'Inaantok na... Zzz'],
  'chat.statusReady':      ['Ready to help!', 'Handang tumulong!'],
  'chat.statusHappy':      ['Happy clucking!', 'Masayang tuka-tuka!'],
  'chat.statusYawning':    ['Yawning...', 'Humihikab...'],
  'chat.statusWeight':     ['Monitoring weight progress!', 'Binabantayan ang timbang!'],
  'chat.statusWorried':    ['A bit worried...', 'Medyo nag-aalala...'],
  'chat.statusProfile':    ['Reviewing profile!', 'Sinusuri ang profile!'],
  'chat.statusWaitingLog': ['Waiting for meal logs!', 'Naghihintay ng meal log!'],
  'chat.statusMenu':       ["Reviewing today's menu!", 'Sinusuri ang menu ngayon!'],
  'chat.statusWaitingGrams': ['Waiting for weight in grams...', 'Naghihintay ng bigat sa gramo...'],
  'chat.statusFlexing':    ['Flexing those feathers!', 'Nagpapa-flex ng balahibo!'],
  'chat.statusSleepyBawk': ['Sleepy bawk...', 'Inaantok na tuka...'],
  'chat.statusMacros':     ['Keeping watch on macros!', 'Binabantayan ang macros!'],
  'chat.statusUpdated':    ['Updated log!', 'Na-update ang log!'],
  'chat.statusConfused':   ['Confused cluck...', 'Nalilitong tuka...'],
  'chat.statusStrategy':   ['Strategizing!', 'Nagpaplano!'],
  'chat.statusTips':       ['Giving exact tips!', 'Nagbibigay ng eksaktong tips!'],
  'chat.statusHealth':     ['Health check!', 'Health check!'],
  'chat.statusHelpful':    ['Feeling helpful!', 'Gustong tumulong!'],
  'chat.statusPump':       ['Feelin the pump!', 'Ramdam ang pump!'],
  'chat.statusBedtime':    ['Bedtime cluck...', 'Oras na ng tulog...'],
  'chat.statusStreak':     ['Log streak ongoing!', 'Tuloy ang log streak!'],
  'chat.statusScan':       ['Logged scan!', 'Na-log ang scan!'],

  'chat.welcome': [
    "Cluck cluck! Hello {name}! I'm Nokma, your personal macro-tracking chicken mascot! 🐔\n\nTell me what you ate (e.g. \"I ate 150g of roasted chicken\") and I'll parse it and log it for you. You can even specify bones, like \"chicken thigh with 20g bones\"!",
    'Tuka tuka! Kumusta {name}! Ako si Nokma, ang iyong personal na macro-tracking chicken mascot! 🐔\n\nSabihin mo kung ano ang kinain mo (hal. "Kumain ako ng 150g na inihaw na manok") at ipo-proseso ko at ilo-log ito para sa iyo. Pwede mo pang tukuyin ang buto, tulad ng "chicken thigh na may 20g buto"!',
  ],
  'chat.suggestion.logChicken':  ['Log 150g grilled chicken breast', 'I-log ang 150g inihaw na chicken breast'],
  'chat.suggestion.logRice':     ['Log 200g of rice for lunch', 'I-log ang 200g kanin para sa tanghalian'],
  'chat.suggestion.remaining':   ['What meals should I eat in order to meet my remaining kcal?', 'Anong pagkain ang dapat kong kainin para maabot ang natitirang kcal ko?'],
  'chat.suggestion.suggestMeal': ['Suggest a meal', 'Magmungkahi ng pagkain'],
  'chat.suggestion.strategies':  ['Do you have any meal strategies?', 'May meal strategy ka ba?'],
  'chat.suggestion.allergies':   ['What are my allergies?', 'Ano ang mga allergy ko?'],

  'chat.outOfDomain': [
    'Cluck? Nokma is here to help with your fitness journey! 🐔✨\n\nI can help you log foods, track your weight, display macro targets, or view today\'s progress.\n\nTry asking me:\n- "What is my weight?"\n- "How are my macros today?"\n- "Log 150g grilled chicken breast"\n- "Show my profile details"',
    'Tuka? Nandito si Nokma para tumulong sa iyong fitness journey! 🐔✨\n\nKaya kitang tulungan mag-log ng pagkain, mag-track ng timbang, magpakita ng macro target, o tingnan ang progreso ngayong araw.\n\nSubukan mong itanong:\n- "Ano ang timbang ko?"\n- "Kumusta ang macros ko ngayon?"\n- "I-log ang 150g inihaw na chicken breast"\n- "Ipakita ang detalye ng profile ko"',
  ],
  'chat.greetingReply': [
    'Cluck cluck! Good {timeOfDay}, {name}! 🐔✨\n\nNokma is feeling motivated and ready to help you track your progress. Let me know what you\'d like to check or log today!',
    'Tuka tuka! Magandang {timeOfDay}, {name}! 🐔✨\n\nMotivated si Nokma at handang tumulong sa pag-track ng progreso mo. Sabihin mo kung ano ang gusto mong tingnan o i-log ngayon!',
  ],
  'chat.timeMorning':   ['morning', 'umaga'],
  'chat.timeAfternoon': ['afternoon', 'hapon'],
  'chat.timeEvening':   ['evening', 'gabi'],
  'chat.weightReply': [
    'Cluck! According to my records, your current weight is **{kg} kg** (approx. {lbs} lbs). 🐔⚖️\n\nYour goal is to **{goal}** weight. Keep up the amazing effort!',
    'Tuka! Ayon sa aking talaan, ang kasalukuyang timbang mo ay **{kg} kg** (humigit-kumulang {lbs} lbs). 🐔⚖️\n\nAng goal mo ay **{goal}** ang timbang. Ipagpatuloy ang magandang pagsisikap!',
  ],
  'chat.noWeight': [
    "Cluck! I don't see a weight recorded in your profile yet. You can set your weight in the Profile tab! 🐔",
    'Tuka! Wala pa akong nakikitang timbang sa profile mo. Pwede mong itakda ang timbang mo sa Profile tab! 🐔',
  ],
  'chat.profileReply': [
    'Bawk! Here is what Nokma knows about your profile: 🐔\n\n👤 **Name**: {name}\n🎂 **Age**: {age}\n📏 **Height**: {height} cm\n⚖️ **Weight**: {weight} kg\n🎯 **Goal**: {goal}\n🌍 **Country**: {country}\n🏥 **Health Condition**: {condition}\n🚫 **Allergies**: {allergies}\n\nNeed to make changes? Head over to the Profile tab! ✨',
    'Tuka! Ito ang alam ni Nokma tungkol sa profile mo: 🐔\n\n👤 **Pangalan**: {name}\n🎂 **Edad**: {age}\n📏 **Taas**: {height} cm\n⚖️ **Timbang**: {weight} kg\n🎯 **Goal**: {goal}\n🌍 **Bansa**: {country}\n🏥 **Kondisyong Pangkalusugan**: {condition}\n🚫 **Mga Allergy**: {allergies}\n\nGusto mong magbago? Pumunta sa Profile tab! ✨',
  ],
  'chat.noMeals': [
    'Cluck! You haven\'t logged any meals today yet. 🐔\n\nTell me what you ate (e.g., "Log 150g grilled chicken breast") and I\'ll list it here!',
    'Tuka! Wala ka pang na-log na pagkain ngayong araw. 🐔\n\nSabihin mo kung ano ang kinain mo (hal. "I-log ang 150g inihaw na chicken breast") at ililista ko dito!',
  ],
  'chat.mealsHeader':  ['Bawk! Here are your logged meals for today: 🐔🍗', 'Tuka! Narito ang mga na-log mong pagkain ngayong araw: 🐔🍗'],
  'chat.mealAtTime':   ['{mealType} (at {time}):', '{mealType} (noong {time}):'],
  'chat.minusBones':   [', minus {grams}g bones', ', bawas {grams}g buto'],
  'chat.missingGrams': [
    "Cluck? Nokma noticed you mentioned **{food}**, but I didn't see the quantity in grams! 🥺\n\nCould you specify the weight in grams? For example:\n- \"Log 150g {food}\"\n- \"I ate 200g of {food} for lunch\"",
    'Tuka? Napansin ni Nokma na binanggit mo ang **{food}**, pero wala akong nakitang dami sa gramo! 🥺\n\nPwede mo bang tukuyin ang bigat sa gramo? Halimbawa:\n- "I-log ang 150g {food}"\n- "Kumain ako ng 200g na {food} para sa tanghalian"',
  ],
  'chat.reportHeader': ['Here is your Daily Macro Report, cluck! 🐔', 'Narito ang iyong Daily Macro Report, tuka! 🐔'],
  'chat.reportBody': [
    '🔥 **Calories**: {cal} / {calTarget} kcal (Remaining: {calRem} kcal)\n🍗 **Protein**: {p}g / {pTarget}g\n🌾 **Carbs**: {c}g / {cTarget}g\n🥑 **Fat**: {f}g / {fTarget}g',
    '🔥 **Calories**: {cal} / {calTarget} kcal (Natitira: {calRem} kcal)\n🍗 **Protina**: {p}g / {pTarget}g\n🌾 **Carbs**: {c}g / {cTarget}g\n🥑 **Taba**: {f}g / {fTarget}g',
  ],
  'chat.proteinHit':    ['Bawk bawk! You hit your protein goal! Nokma is flexing! 🐔💪', 'Tuka tuka! Naabot mo ang protein goal mo! Nagpapa-flex si Nokma! 🐔💪'],
  'chat.proteinNeeded': ['Peck at that protein! You still need {grams}g more!', 'Tukain ang protina! Kailangan mo pa ng {grams}g!'],
  'chat.mealMoved':     ["Bawk! I've moved your last meal to **{mealType}**! 🐔✅", 'Tuka! Inilipat ko ang huli mong pagkain sa **{mealType}**! 🐔✅'],
  'chat.noMealsToEdit': ["Cluck? I don't see any meals logged today to change! 🐔", 'Tuka? Wala akong nakikitang na-log na pagkain ngayong araw na mababago! 🐔'],
  'chat.allergyReply': [
    'Cluck! Here is your health summary, {name}! 🐔🏥\n\n🏥 **Health Condition**: {condition}\n\n🚫 **Registered Allergies**:\n{allergies}\n\nNokma always filters your allergens out of meal recommendations! You can update these in the Profile tab.',
    'Tuka! Narito ang buod ng iyong kalusugan, {name}! 🐔🏥\n\n🏥 **Kondisyong Pangkalusugan**: {condition}\n\n🚫 **Mga Nakarehistrong Allergy**:\n{allergies}\n\nPalaging inaalis ni Nokma ang iyong mga allergen sa mga meal recommendation! Pwede mong i-update ito sa Profile tab.',
  ],
  'chat.generalTips': [
    'Cluck cluck! Nokma is here! 🐔\n\n💡 **Hoo\'s Fitness Tips**:\n1. Hit your protein targets (aim for 2.0g per kg of body weight).\n2. If you weigh food with bones, type "with 20g bones" to subtract bone weight!\n3. Cooked methods change macros: fried food has added fats compared to boiled.\n\nTry telling me: "Log 150g boiled chicken breast for dinner"!',
    'Tuka tuka! Nandito si Nokma! 🐔\n\n💡 **Mga Fitness Tips ni Hoo**:\n1. Abutin ang iyong protein target (layunin ang 2.0g kada kg ng timbang).\n2. Kung may buto ang tinitimbang mong pagkain, i-type ang "may 20g buto" para ibawas ang bigat ng buto!\n3. Nagbabago ang macros depende sa pagluluto: mas mataas ang taba ng pinirito kaysa nilaga.\n\nSubukan mong sabihin: "I-log ang 150g nilagang chicken breast para sa hapunan"!',
  ],
  'chat.logSuccess': [
    'Bawk! Successfully logged for your **{mealType}**! 🐔🎉',
    'Tuka! Matagumpay na na-log para sa iyong **{mealType}**! 🐔🎉',
  ],
  /** Suffix inside the parentheses of a logged item line. Leading space is intentional. */
  'chat.logItemBones': [' with {grams}g bones', ' may {grams}g buto'],
  'chat.logTotals': [
    '🔥 **Total Calories**: {cal} kcal\n💪 **Total Protein**: {p}g\n🌾 **Total Carbs**: {c}g\n🥑 **Total Fat**: {f}g',
    '🔥 **Kabuuang Calories**: {cal} kcal\n💪 **Kabuuang Protina**: {p}g\n🌾 **Kabuuang Carbs**: {c}g\n🥑 **Kabuuang Taba**: {f}g',
  ],
  'chat.greatProtein': ['Cock-a-doodle-doo! Amazing protein source! Nokma is flexing! 🐔💪', 'Tik-ti-la-ok! Napakagandang protein source! Nagpapa-flex si Nokma! 🐔💪'],
  'chat.loggedKeepGoing': ['Logged! Keep checking your macros!', 'Na-log! Ipagpatuloy ang pagbantay sa macros mo!'],
  'chat.logFailed': [
    'Cluck... I failed to log those items. Error: {error}. Try entering them manually in the Log Meal screen!',
    'Tuka... Nabigo akong i-log ang mga item na iyon. Error: {error}. Subukan mong ilagay nang manual sa Log Meal screen!',
  ],
  'chat.scanLogged': [
    'Bawk! Successfully logged your scanned item **{name}** to your **{mealType}**! 🐔🎉\n\n🔥 **Calories**: {cal} kcal\n💪 **Protein**: {p}g\n🌾 **Carbs**: {c}g\n🥑 **Fat**: {f}g',
    'Tuka! Matagumpay na na-log ang na-scan mong item na **{name}** sa iyong **{mealType}**! 🐔🎉\n\n🔥 **Calories**: {cal} kcal\n💪 **Protina**: {p}g\n🌾 **Carbs**: {c}g\n🥑 **Taba**: {f}g',
  ],
  'chat.scannedPrefix': ['📸 Scanned Nutrition Facts: {name}', '📸 Na-scan na Nutrition Facts: {name}'],
  'chat.allergenLoggedTitle': ['Allergy alert ⚠️', 'Alerto sa allergy ⚠️'],
  'chat.allergenLoggedBody': ['This meal contains allergens you registered: {allergens}. Please be careful!', 'Naglalaman ang pagkain na ito ng allergen na mayroon ka: {allergens}. Mag-ingat!'],
  'chat.recNoMatch': [
    "Hmm, I couldn't find recipes that match your allergies for your remaining calories. You may need to track manually or check the Search tab for options!",
    'Hmm, wala akong nahanap na recipe na tugma sa iyong mga allergy para sa natitira mong calories. Baka kailangan mong mag-track nang manual o tingnan ang Search tab!',
  ],
  'chat.recNextMeal': [
    'You still have {count} meals left. For your next meal (**~{kcal} kcal**), try these: 🐔',
    'May {count} pa kayong pagkain na natitira. Para sa susunod mong pagkain (**~{kcal} kcal**), subukan ito: 🐔',
  ],
  'chat.recExact': [
    'To exactly hit your remaining **{kcal} kcal**, here are some scaled recipes: 🐔',
    'Para eksaktong maabot ang natitira mong **{kcal} kcal**, narito ang ilang scaled na recipe: 🐔',
  ],
  'chat.recTotalPortion': ['Total Portion: {grams}g', 'Kabuuang Bahagi: {grams}g'],
  'chat.recIngredients':  ['Ingredients:', 'Mga Sangkap:'],
  'chat.recAllergenFree': [
    '✅ All suggestions above are free of your allergens ({allergens}).',
    '✅ Lahat ng mungkahi sa itaas ay walang mga allergen mo ({allergens}).',
  ],
  'chat.recFailed': ["Cluck... I couldn't fetch recommendations right now!", 'Tuka... Hindi ako makakuha ng rekomendasyon ngayon!'],
  'chat.stratHeader':  ['Cluck! You have **{kcal} kcal** left for the day.', 'Tuka! May natitira kang **{kcal} kcal** para sa araw na ito.'],
  'chat.stratSplit': [
    'Since you still need to eat **{meals}**, I recommend splitting your calories:\n\nAim for about **{perMeal} kcal** per meal. Try to prioritize protein in each!\n\nYou can say *"Suggest a meal"* to get a recipe for your next meal!',
    'Dahil kailangan mo pang kumain ng **{meals}**, iminumungkahi kong hatiin ang iyong calories:\n\nLayunin ang humigit-kumulang **{perMeal} kcal** kada pagkain. Unahin ang protina sa bawat isa!\n\nPwede mong sabihin ang *"Magmungkahi ng pagkain"* para makakuha ng recipe!',
  ],
  'chat.stratSingle': [
    'You only have **{meal}** left! You can use all **{kcal} kcal** on it. Focus on hitting your remaining protein target of {protein}g.\n\nSay *"Suggest a meal"* for ideas!',
    'Ang natitira mo na lang ay **{meal}**! Pwede mong gamitin ang buong **{kcal} kcal** dito. Pagtuunan ang natitirang protein target na {protein}g.\n\nSabihin ang *"Magmungkahi ng pagkain"* para sa ideya!',
  ],
  'chat.condDiabetes':     ["🩺 Since you have **Diabetes**, I'm prioritizing low-GI, low-sugar options.", '🩺 Dahil may **Diabetes** ka, inuuna ko ang low-GI at low-sugar na opsyon.'],
  'chat.condHypertension': ["🩺 Since you have **Hypertension**, I'm recommending low-sodium meals.", '🩺 Dahil may **Hypertension** ka, nagrerekomenda ako ng low-sodium na pagkain.'],
  'chat.condKidney':       ["🩺 Since you have **Kidney Disease**, I'm keeping protein moderate and avoiding high-phosphorus foods.", '🩺 Dahil may **Sakit sa Bato** ka, pinapanatili kong katamtaman ang protina at iniiwasan ang high-phosphorus na pagkain.'],
  'chat.condOther':        ["🩺 Noted your condition: **{condition}**. I'll keep recommendations as balanced as possible.", '🩺 Naitala ang iyong kondisyon: **{condition}**. Pananatilihin kong balanse ang mga rekomendasyon.'],
  'chat.filteringOut':     ['🚫 Filtering out recipes with: **{allergens}**', '🚫 Inaalis ang mga recipe na may: **{allergens}**'],
} as const;

export type StringKey = keyof typeof STRINGS;
